package tlfgen

// Skill is a single skill.
type Skill struct {
	value  int
	weight int
}

func (s *Skill) add(n int) {
	s.value += n
}

// PersonalityType is a list of skill names and a starting bonus.
type PersonalityType struct {
	bonus   int
	desc    string
	skills  []string
	special string
}

// Assignment is a list of skill names and a starting bonus.
type Assignment struct {
	bonus  int
	skills []string
}

// Profession is a list of skills and an [offset, num] slice of
// optional skills from which num should be sampled.
type Profession struct {
	skills    []string
	optOffset int
	optNum    int
}

// Professions is a map of professions.
var Professions = map[string]Profession{
	"Occultist": Profession{
		skills: []string{
			"Fast Talk",
			"Insight",
			"Knowledge: Anthropology",
			"Knowledge: History",
			"Knowledge: Occult",
			"Language: *",
			"Language: Own",
			"Research",
			"Computer Use: *",
			"Craft: *",
			"Knowledge: Archaeology",
			"Medicine",
			"Science: any",
		},
		optOffset: 8,
		optNum:    2,
	},
	"Philosopher": Profession{
		skills: []string{
			"Insight",
			"Knowledge: History",
			"Knowledge: Philosophy",
			"Language: *",
			"Language: Own",
			"Persuade",
			"Research",
			"Teach",
			"Knowledge: *",
			"Science: *",
		},
		optOffset: 8,
		optNum:    2,
	},
}

// PersonalityTypes is a map of PTypes.
var PersonalityTypes = map[string]PersonalityType{
	"Bruiser": PersonalityType{
		bonus: 20,
		desc:  "Your character believes that solving problems is best handled through quick application of physical force.",
		skills: []string{
			"Brawl",
			"Climb",
			"COMBAT",
			"COMBAT",
			"Dodge",
			"Grapple",
			"Insight",
			"Jump",
			"Ride",
			"Sense",
			"Stealth",
			"Swim",
			"Throw",
		},
		special: "",
	},
	"Nutter": PersonalityType{
		bonus: 20,
		desc:  "Your character can safely be categorised as insane, though they are functional and able to work within the organisation of the Laundry. Rational thought and problem-solving methods are neglected: insane leaps of logic are the primary means of attaining goals.",
		skills: []string{
			"Command",
			"Fast Talk",
			"Hide",
			"Insight",
			"Knowledge: *",
			"Knowledge: *",
			"Research",
			"Science: *",
			"Science: *",
			"Sense",
			"Spot",
			"Stealth",
			"Strategy",
		},
		special: "Reduce starting SAN by 20 points and assign an appropriate mental disorder. Depending on the disorder, your character may be in therapy or on medication to deal with the symptoms.",
	},
}

// Assignments is a map of assignments.
var Assignments = map[string]Assignment{
	"Archives": Assignment{
		bonus: 10,
		skills: []string{
			"Bureaucracy",
			"Knowledge: *",
			"Knowledge: *",
			"Navigate",
			"Research",
			"Stealth",
		},
	},
	"Computational Demonology": Assignment{
		bonus: 10,
		skills: []string{
			"Computer Use: *",
			"Computer Use: Magic",
			"Science: Mathematics",
			"Science: Thaumaturgy",
			"Sorcery",
		},
	},
	"all": Assignment{
		bonus: 5,
		skills: []string{
			"Bureaucracy",
			"Computer Use",
			"Fine Manipulation",
			"Firearm: *",
			"Knowledge: Accounting",
			"Knowledge: Espionage",
			"Knowledge: Law",
			"Knowledge: Occult",
			"Knowledge: Politics",
			"Spot",
		},
	},
}

// CombatSkills list of all the possible combat skills.
var CombatSkills = []string{
	"Artillery: Cannon",
	"Artillery: Cannon",
	"Artillery: Other",
	"Artillery: Rocket Launcher",
	"Artillery: Turret",
	"Artillery: Vehicular Weapon",
	"Artillery: Other",
	"Artillery: Rocket Launcher",
	"Artillery: Turret",
	"Artillery: Vehicular Weapon",
	"Firearm: Assault Rifle",
	"Firearm: Esoteric",
	"Firearm: Exotic",
	"Firearm: Pistol",
	"Firearm: Rifle",
	"Firearm: Shotgun",
	"Firearm: Submachine Gun",
	"Heavy Weapon: Bazooka",
	"Heavy Weapon: Grenade Launcher",
	"Heavy Weapon: Heavy Machine Gun",
	"Heavy Weapon: Minigun",
	"Heavy Weapon: Other",
	"Heavy Weapon: Rocket Launcher",
	"Melee Weapon: Axe",
	"Melee Weapon: Club",
	"Melee Weapon: Garrote",
	"Melee Weapon: Knife",
	"Melee Weapon: Other",
	"Melee Weapon: Spear",
	"Melee Weapon: Staff",
	"Melee Weapon: Sword",
	"Melee Weapon: Whip",
	"Missile Weapon: Archery",
	"Missile Weapon: Blowgun",
	"Missile Weapon: Boomerang",
	"Missile Weapon: Bow",
	"Missile Weapon: Crossbow",
	"Missile Weapon: Dart",
	"Missile Weapon: Javelin",
	"Missile Weapon: Other",
	"Missile Weapon: Shuriken",
	"Missile Weapon: Sling",
	"Missile Weapon: Spear",
	"Missile Weapon: Throwing Axe",
	"Missile Weapon: Throwing Knife",
}

// Skills is a master map of skills.
var Skills = map[string]Skill{
	"Appraise":                                  Skill{value: 15},
	"Art: Calligraphy":                          Skill{value: 5},
	"Art: Drawing":                              Skill{value: 5},
	"Art: Other":                                Skill{value: 5},
	"Art: Painting":                             Skill{value: 5},
	"Art: Photography":                          Skill{value: 5},
	"Art: Sculpture":                            Skill{value: 5},
	"Art: Writing":                              Skill{value: 5},
	"Artillery: Cannon":                         Skill{value: 0},
	"Artillery: Other":                          Skill{value: 0},
	"Artillery: Rocket Launcher":                Skill{value: 0},
	"Artillery: Turret":                         Skill{value: 0},
	"Artillery: Vehicular Weapon":               Skill{value: 0},
	"Athletics: Acrobatics":                     Skill{value: 10},
	"Athletics: American and Canadian Football": Skill{value: 10},
	"Athletics: Baseball":                       Skill{value: 10},
	"Athletics: Basketball":                     Skill{value: 10},
	"Athletics: Bowling":                        Skill{value: 10},
	"Athletics: Cricket":                        Skill{value: 10},
	"Athletics: Cycling":                        Skill{value: 10},
	"Athletics: Golf":                           Skill{value: 10},
	"Athletics: Hockey":                         Skill{value: 10},
	"Athletics: Rugby":                          Skill{value: 10},
	"Athletics: Skating":                        Skill{value: 10},
	"Athletics: Skiing":                         Skill{value: 10},
	"Athletics: Soccer":                         Skill{value: 10},
	"Athletics: Tennis":                         Skill{value: 10},
	"Athletics: Track & Field":                  Skill{value: 10},
	"Bargain":                                   Skill{value: 5},
	"Brawl":                                     Skill{value: 25},
	"Bureaucracy":                               Skill{value: 5},
	"Climb":                                     Skill{value: 40},
	"Command":                                   Skill{value: 5},
	"Computer Use: Art":                         Skill{value: 5},
	"Computer Use: Design":                      Skill{value: 5},
	"Computer Use: Gaming":                      Skill{value: 5},
	"Computer Use: Hacking":                     Skill{value: 5},
	"Computer Use: Magic":                       Skill{value: 5},
	"Computer Use: Maintenance":                 Skill{value: 5},
	"Computer Use: Other":                       Skill{value: 5},
	"Computer Use: Programming":                 Skill{value: 5},
	"Computer Use: Repair":                      Skill{value: 5},
	"Craft: Carpentry":                          Skill{value: 5},
	"Craft: Cooking":                            Skill{value: 5},
	"Craft: Leatherworking":                     Skill{value: 5},
	"Craft: Pottery":                            Skill{value: 5},
	"Craft: Sewing":                             Skill{value: 5},
	"Craft: Woodworking":                        Skill{value: 5},
	"Cthulhu Mythos":                            Skill{value: 0},
	"Demolition":                                Skill{value: 1},
	"Disguise":                                  Skill{value: 5},
	"Dodge":                                     Skill{value: -1, weight: 10},
	"Drive: Automobile":                         Skill{value: 20},
	"Drive: Industrial Mover":                   Skill{value: 20},
	"Drive: Motorcycle":                         Skill{value: 20},
	"Drive: Other":                              Skill{value: 20},
	"Drive: Tank":                               Skill{value: 20},
	"Etiquette":                                 Skill{value: 5},
	"Fast Talk":                                 Skill{value: 5},
	"Fine Manipulation":                         Skill{value: 5},
	"Firearm: Assault Rifle":                    Skill{value: 15, weight: 5},
	"Firearm: Esoteric":                         Skill{value: 0, weight: 5},
	"Firearm: Exotic":                           Skill{value: 5},
	"Firearm: Pistol":                           Skill{value: 20, weight: 50},
	"Firearm: Rifle":                            Skill{value: 25, weight: 20},
	"Firearm: Shotgun":                          Skill{value: 30, weight: 20},
	"Firearm: Submachine Gun":                   Skill{value: 15},
	"First Aid":                                 Skill{value: 30},
	"Gaming":                                    Skill{value: 10},
	"Geology":                                   Skill{value: 0},
	"Grapple":                                   Skill{value: 25},
	"Heavy Machine: Boiler":                     Skill{value: 5},
	"Heavy Machine: Bulldozer":                  Skill{value: 5},
	"Heavy Machine: Crane":                      Skill{value: 5},
	"Heavy Machine: Engine":                     Skill{value: 5},
	"Heavy Machine: Other":                      Skill{value: 5},
	"Heavy Machine: Turbine":                    Skill{value: 5},
	"Heavy Machine: Wrecker":                    Skill{value: 5},
	"Heavy Weapon: Bazooka":                     Skill{value: 0},
	"Heavy Weapon: Grenade Launcher":            Skill{value: 0},
	"Heavy Weapon: Heavy Machine Gun":           Skill{value: 0},
	"Heavy Weapon: Minigun":                     Skill{value: 0},
	"Heavy Weapon: Other":                       Skill{value: 0},
	"Heavy Weapon: Rocket Launcher":             Skill{value: 0},
	"Hide":                           Skill{value: 10},
	"Insight":                        Skill{value: 5},
	"Jump":                           Skill{value: 25},
	"Knowledge: Accounting":          Skill{value: 10},
	"Knowledge: Anthropology":        Skill{value: 1},
	"Knowledge: Archaeology":         Skill{value: 1},
	"Knowledge: Art History":         Skill{value: 1},
	"Knowledge: Business":            Skill{value: 1},
	"Knowledge: Espionage":           Skill{value: 0},
	"Knowledge: Folklore":            Skill{value: 5},
	"Knowledge: Group":               Skill{value: 0},
	"Knowledge: History":             Skill{value: 20},
	"Knowledge: Law":                 Skill{value: 5},
	"Knowledge: Linguistics":         Skill{value: 0},
	"Knowledge: Literature":          Skill{value: 5},
	"Knowledge: Natural History":     Skill{value: 10},
	"Knowledge: Occult":              Skill{value: 5},
	"Knowledge: Philosophy":          Skill{value: 1},
	"Knowledge: Politics":            Skill{value: 5},
	"Knowledge: Region":              Skill{value: 0},
	"Knowledge: Religion":            Skill{value: 5},
	"Knowledge: Streetwise":          Skill{value: 5},
	"Language: A":                    Skill{value: 0},
	"Language: B":                    Skill{value: 0},
	"Language: C":                    Skill{value: 0},
	"Language: D":                    Skill{value: 0},
	"Language: E":                    Skill{value: 0},
	"Language: Own":                  Skill{value: -1},
	"Listen":                         Skill{value: 25},
	"Medicine: Dermatology":          Skill{value: 5},
	"Medicine: Family Medicine":      Skill{value: 5},
	"Medicine: Immunology":           Skill{value: 5},
	"Medicine: Internal Medicine":    Skill{value: 5},
	"Medicine: Neurology":            Skill{value: 5},
	"Medicine: Nuclear Medicine":     Skill{value: 5},
	"Medicine: Oncology":             Skill{value: 5},
	"Medicine: Other":                Skill{value: 5},
	"Medicine: Pathology":            Skill{value: 5},
	"Medicine: Pediatrics":           Skill{value: 5},
	"Medicine: Radiology":            Skill{value: 5},
	"Medicine: Surgery":              Skill{value: 5},
	"Melee Weapon: Axe":              Skill{value: 5, weight: 5},
	"Melee Weapon: Club":             Skill{value: 5, weight: 10},
	"Melee Weapon: Garrote":          Skill{value: 5},
	"Melee Weapon: Knife":            Skill{value: 5, weight: 20},
	"Melee Weapon: Other":            Skill{value: 5},
	"Melee Weapon: Spear":            Skill{value: 5},
	"Melee Weapon: Staff":            Skill{value: 5, weight: 5},
	"Melee Weapon: Sword":            Skill{value: 5, weight: 5},
	"Melee Weapon: Whip":             Skill{value: 5},
	"Missile Weapon: Blowgun":        Skill{value: 5},
	"Missile Weapon: Boomerang":      Skill{value: 5},
	"Missile Weapon: Bow":            Skill{value: 5, weight: 20},
	"Missile Weapon: Crossbow":       Skill{value: 5},
	"Missile Weapon: Dart":           Skill{value: 5},
	"Missile Weapon: Javelin":        Skill{value: 5},
	"Missile Weapon: Other":          Skill{value: 5},
	"Missile Weapon: Shuriken":       Skill{value: 5},
	"Missile Weapon: Sling":          Skill{value: 5},
	"Missile Weapon: Spear":          Skill{value: 5},
	"Missile Weapon: Throwing Axe":   Skill{value: 5},
	"Missile Weapon: Throwing Knife": Skill{value: 5, weight: 10},
	"Navigate":                       Skill{value: 10},
	"Perform: Act":                   Skill{value: 5},
	"Perform: Dance":                 Skill{value: 5},
	"Perform: Juggle":                Skill{value: 5},
	"Perform: Other":                 Skill{value: 5},
	"Perform: Play Instrument":       Skill{value: 5},
	"Perform: Recite":                Skill{value: 5},
	"Perform: Sing":                  Skill{value: 5},
	"Persuade":                       Skill{value: 15},
	"Pilot: Battleship":              Skill{value: 0},
	"Pilot: Helicopter":              Skill{value: 0},
	"Pilot: Hot Air Balloon":         Skill{value: 0},
	"Pilot: Hovercraft":              Skill{value: 0},
	"Pilot: Jet Airliner":            Skill{value: 0},
	"Pilot: Jet Boat":                Skill{value: 0},
	"Pilot: Jet Fighter":             Skill{value: 0},
	"Pilot: Ocean Liner":             Skill{value: 0},
	"Pilot: Propeller Plane":         Skill{value: 0},
	"Research":                       Skill{value: 25, weight: 10},
	"Ride":                           Skill{value: 5},
	"Science: Astronomy":             Skill{value: 1},
	"Science: Biology":               Skill{value: 1},
	"Science: Botany":                Skill{value: 1},
	"Science: Chemistry":             Skill{value: 1},
	"Science: Cyptography":           Skill{value: 1},
	"Science: Forensics":             Skill{value: 1},
	"Science: Genetics":              Skill{value: 1},
	"Science: Geology":               Skill{value: 1},
	"Science: Mathematics":           Skill{value: 10},
	"Science: Meteorology":           Skill{value: 1},
	"Science: Pharmacy":              Skill{value: 1},
	"Science: Physics":               Skill{value: 1},
	"Science: Planetology":           Skill{value: 1},
	"Science: Psychology":            Skill{value: 5},
	"Science: Thaumaturgy":           Skill{value: 0},
	"Science: Zoology":               Skill{value: 5},
	"Sense":                          Skill{value: 10},
	"Sleight of Hand":                Skill{value: 5},
	"Sorcery":                        Skill{value: 0},
	"Spot":                           Skill{value: 25, weight: 10},
	"Status":                         Skill{value: 15},
	"Stealth":                        Skill{value: 10},
	"Strategy":                       Skill{value: 5},
	"Swim":                           Skill{value: 25},
	"Teach":                          Skill{value: 10},
	"Technology Use: Communications":      Skill{value: 5},
	"Technology Use: Electronic Security": Skill{value: 5},
	"Technology Use: Electronics":         Skill{value: 5},
	"Technology Use: Other":               Skill{value: 5},
	"Technology Use: Sensor Systems":      Skill{value: 5},
	"Technology Use: Surveillance":        Skill{value: 5},
	"Technology Use: Traps":               Skill{value: 5},
	"Throw":                               Skill{value: 25},
	"Track":                               Skill{value: 10},
}
